version: '3.9'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=poke
      - POSTGRES_PASSWORD=poke
      - POSTGRES_DB=poke_api
    volumes:
       - pgdata:/data/postgres

  app:
    build: .
    container_name: pokemon_api_app
    ports:
      - 4000:4000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database


volumes:
  pgdata:
    driver: local